// src/routes/discord.svelte
<script>
	import Box from '../components/Box.svelte';
	import Button from '../components/Button.svelte';
	import Card from '../components/Card.svelte';
	import Feature from '../components/Feature.svelte';
	import Link from '../components/Link.svelte';
</script>

<svelte:head>
	<title>Discord bot • Christmas Countdown</title>
	<meta name="title" content="Discord bot • Christmas Countdown" />
	<meta name="og:title" content="Discord bot • Christmas Countdown" />
	<meta name="twitter:title" content="Discord bot • Christmas Countdown" />
	<meta
		name="description"
		content="Get the number of sleeps left until Christmas sent to a selected channel every morning - in your language and your timezone."
	/>
	<meta
		name="og:description"
		content="Get the number of sleeps left until Christmas sent to a selected channel every morning - in your language and your timezone."
	/>
	<meta
		name="twitter:description"
		content="Get the number of sleeps left until Christmas sent to a selected channel every morning - in your language and your timezone."
	/>
	<meta name="url" content="https://www.christmascountdown.live/discord" />
	<meta name="og:url" content="https://www.christmascountdown.live/discord" />
</svelte:head>

<div class="container mx-auto">
	<h1 class="select-none text-center">
		<p class="text-xl uppercase p-2">The original</p>
		<p class="font-christmas text-7xl p-2">Christmas Countdown</p>
		<p class="text-2xl uppercase p-2">bot for Discord</p>
	</h1>

	<Box>
		<div class="my-8 text-center p-8">
			<div class="my-6">
			<p>
				Add the Christmas Countdown bot for Discord to your server to get the number of sleeps left
				until Christmas sent to a selected channel every morning. The bot has been added to over
				8000 Discord servers since 2018.
			</p>
		</div>

		<a href="/invite">
			<Button colour="bg-blurple" text="Add to Discord" />
		</a>
		</div>
	</Box>
	<h2 class="text-xl font-bold text-center mb-4">Features</h2>

	<div id="features" class="container mx-auto w-full m-8 grid grid-cols-1 sm:grid-cols-2 gap-4">
		<Feature title="Server and user timezones">
			<p>
				Make the commands more accurate by setting your user timezone. This will be used when you
				use a Christmas command on any server.
			</p>
			<p>
				The server's timezone is used for the automatic countdown in the morning, and will be used
				as the default when a user who has not set a personal timezone uses a command.
			</p>
			<br />
			<p class="text-right">
				<Link href="https://docs.christmascountdown.live/discord/timezones">
					Learn more <i class="fas fa-arrow-right" />
				</Link>
			</p>
		</Feature>
		<Feature title="Server and user locales">
			<p>
				Similarly to the timezones, users can set their own language, and administrators can set the
				server's default.
			</p>
			<p>
				If the bot hasn't been translated to your language yet, you can contribute on <Link
					href="https://github.com/christmas-countdown/bot">GitHub</Link
				>.
			</p>
			<br />
			<p class="text-right">
				<Link href="https://i18n.capestar.net/engage/christmas-countdown/"
					>Translate <i class="fas fa-arrow-right" /></Link
				>
			</p>
		</Feature>
		<Feature title="Logical commands">
			<p>The bot is very easy to use and has over 20 well-documented commands.</p>
			<img
				src="https://static.eartharoid.me/sharex/21/10/bot-help-cmd.png"
				alt="Commands"
				class="my-4"
			/>
			<p class="text-right">
				<Link href="https://docs.christmascountdown.live/discord/commands"
					>Learn more <i class="fas fa-arrow-right" /></Link
				>
			</p>
		</Feature>
		<Feature title="Time left to Christmas in...">
			<p>months, weeks, sleeps, days, hours, minutes, seconds, or the total time left.</p>
			<img
				src="https://static.eartharoid.me/sharex/21/10/bot-total-cmd.png"
				alt="Total"
				class="my-4"
			/>
			<img
				src="https://static.eartharoid.me/sharex/21/10/bot-hours-cmd.png"
				alt="Hours"
				class="my-4"
			/>
		</Feature>
		<Feature title="Daily countdown">
			<p>
				<Link href="https://docs.christmascountdown.live/discord/enable-the-countdown"
					>Set the countdown channel</Link
				> and get a countdown message ready for when you wake up every morning.
			</p>
			<img
				src="https://static.eartharoid.me/sharex/21/10/bot-countdown.png"
				alt="Countdown"
				class="my-4"
			/>
			<p class="text-right">
				<Link href="https://docs.christmascountdown.live/discord/enable-the-countdown"
					>Learn more <i class="fas fa-arrow-right" /></Link
				>
			</p>
		</Feature>
		<Feature title="Jokes">
			<p>
				Use the <Link href="https://docs.christmascountdown.live/discord/commands#joke"
					><code class="text-primary">/joke</code></Link
				> command to get a random Christmas joke.
			</p>
			<img
				src="https://static.eartharoid.me/sharex/21/10/bot-joke-cmd.png"
				alt="Joke"
				class="my-4"
			/>
		</Feature>
	</div>
	<div class="text-center">
		<a href="/invite">
			<Button colour="bg-blurple" text="Add to Discord" />
		</a>
	</div>
	<div class="grid grid-cols-1 gap-4 sm:w-1/2 mx-auto mt-8">
		<a
			href="https://top.gg/bot/648134637654114309"
			class="mx-2 transform hover:scale-105 duration-300"
		>
			<Card background="bg-blurple" border="border-blurple">
				<div class="p-6">
					<h2 class="font-bold text-xl mb-2">
						<img
							src="https://images.discordapp.net/avatars/648134637654114309/6d6986c735dec65ba5e2e731db15909c.png?size=48"
							alt="Logo"
							class="rounded-3xl mr-4 inline"
						/>Christmas Radio <i class="fas fa-external-link-alt" />
					</h2>
					<p>
						Play Christmas music 24/7 in your Discord server with the <Link
							href="https://top.gg/bot/648134637654114309">Christmas Radio bot.</Link
						>
					</p>
				</div>
			</Card>
		</a>
	</div>
</div>

// src/views/Discord.vue
<template>
  <div class='content'>
    <Navbar />

	<mdb-container> <!-- fluid -->
		<div id='title'>
			<div>
				<h4>The original</h4>
				<h1>Christmas Countdown</h1>
				<h3>bot for Discord</h3>
			</div>

			<br /><br />

			<div>
				<!-- <h2>Features</h2> -->
				<p>
					Get the number of sleeps left until Christmas sent to a selected channel every morning - in <span class='hl'>your language</span> and <span class='hl'>your timezone</span>.
					<!-- The Christmas Countdown bot for Discord has some cool features... -->
				</p>
			
				<a href='/invite'>
					<mdb-btn style='background-color:#7289DA;color:white;'>Add to Discord</mdb-btn> <!-- color='primary' -->
				</a>

			</div>
		</div>

		<mdb-row>
			<mdb-col lg='8' class='box z-depth-5 hvr-grow left'>
				<mdb-row>
					<mdb-col>
						<div class='header'>
							<h6>Server and user</h6>
							<h4>timezones</h4>
						</div>
						<p>
							Make the commands more accurate by setting your user timezone. This will be used when you use a Christmas command on any server.
						</p>
						<p>
							The server's timezone is used for the automatic countdown in the morning, and will be used as the default when a user who has not set a personal timezone uses a command.
						</p>
					</mdb-col>
				</mdb-row>
			</mdb-col>
		</mdb-row>

		<mdb-row>
			<mdb-col lg='4'>
			</mdb-col>
			<mdb-col class='box z-depth-5 hvr-grow right'>
				<mdb-row>
					<mdb-col>
						<div class='header'>
							<h6>Server and user</h6>
							<h4>locales</h4>
						</div>
						<p>
							Similarly to the timezones, users can set their own language, and administrators can set the server's default.
						</p>
						<p>
							If the bot hasn't been translated to your language yet, you can contribute on <a href='https://github.com/eartharoid/ChristmasCountdownBot'>GitHub</a>.
						</p>
					</mdb-col>
				</mdb-row>
			</mdb-col>
		</mdb-row>

		<mdb-row>
			<mdb-col lg='8' class='box z-depth-5 hvr-grow left'>
				<mdb-row>
					<mdb-col>
					<div class='header'>
						<h6>Time left to Christmas in</h6>
						<h4>sleeps? days? hours?</h4>
					</div>
						<p>
							Get the number of weeks, sleeps, days, hours, minutes, seconds, or the total time left until Christmas.
						</p>
					</mdb-col>
				</mdb-row>
			</mdb-col>
		</mdb-row>
		
		<mdb-row>
			<mdb-col lg='4'>
				
			</mdb-col>
			<mdb-col class='box z-depth-5 hvr-grow right'>
				<mdb-row>
					<mdb-col>
						<div class='header'>
							<h4>Logical</h4>
							<h6>commands</h6>
						</div>
						<p>
							The bot is easy to use and has a useful help command, with many links to the <a href='https://docs.christmascountdown.live'>documentation</a> where everything is explained in more detail.
						</p>
					</mdb-col>
				</mdb-row>
			</mdb-col>
		</mdb-row>
	</mdb-container>

	<mdb-container>
		<mdb-row>
			<mdb-col col='md'>
				<img src='https://i.imgur.com/hfF9C3k.png' class='rounded img-fluid zoom' />
			</mdb-col>
			<mdb-col col='md'>
				<img src='https://i.imgur.com/oIXzBfV.png' class='rounded img-fluid zoom' />
			</mdb-col>
		</mdb-row>

		<mdb-row>
			<mdb-col col='md'>
				<img src='https://i.imgur.com/TK9SW2u.png' class='rounded img-fluid zoom' />
			</mdb-col>
			<mdb-col col='md'>
				<img src='https://i.imgur.com/CVDy45B.png' class='rounded img-fluid zoom' />
			</mdb-col>
		</mdb-row>

		<div id='title' style='margin-top:3rem;'>
			<p>
				Why haven't you added it yet?
			</p>
			<a href='/invite'>
				<mdb-btn style='background-color:#7289DA;color:white;'>Add to Discord</mdb-btn> <!-- color='primary' -->
			</a>
		</div>
	</mdb-container>
	<Footer />
  </div>
</template>

<script>
// @ is an alias to /src
import Navbar from '@/components/Navbar.vue';
import Footer from '@/components/Footer.vue';

import {
	mdbBtn,
	mdbContainer,
	mdbCol,
	mdbRow,
} from 'mdbvue';

export default {
  name: 'Discord',
  components: {
	Navbar,
	Footer,
	mdbBtn,
	mdbContainer,
	mdbCol,
	mdbRow,
  }
};
</script>

<style scoped>
	.content {
		text-shadow: 5px 5px 10px black;
	}

	#title {
		text-align: center;
		margin-bottom: 2rem;
	}

	h1 {
		font-family: 'MerryChristmas';
		font-size: 5rem;
	}

	h2, h3, h4, h5, h6 {
		text-transform: uppercase;	
	}

	.box {
		background: rgba(0, 0, 0, 0.8);
		/* padding: 5%; */
		padding: 3%;
		/* border-radius: 15px; */
		margin: 1rem 0 2rem 0;
		box-shadow: 2px 3px 15px rgba(0, 0, 0, 0.8);
	}

	.header {
		margin-bottom: 2rem;
	}

	.left {
		text-align: left;
	}

	.right {
		text-align: right;
		float: right;
	}

	.img-fluid {
		box-shadow: 2px 3px 15px rgba(0, 0, 0, 0.8);
		margin-top: 2rem;
	}

</style>
