// src/routes/(main)/donate/+page.svelte
<script>
	import Button from '$components/Button.svelte';
	import Link from '$components/Link.svelte';
</script>

<svelte:head>
	<title>Donate • Christmas Countdown</title>
	<meta name="title" content="Donate • Christmas Countdown" />
	<meta name="og:title" content="Donate • Christmas Countdown" />
	<meta name="twitter:title" content="Donate • Christmas Countdown" />
	<meta
		name="description"
		content="Send a donation and unlock premium features for the Christmas Countdown Discord bot."
	/>
	<meta
		name="og:description"
		content="Send a donation and unlock premium features for the Christmas Countdown Discord bot."
	/>
	<meta
		name="twitter:description"
		content="Send a donation and unlock premium features for the Christmas Countdown Discord bot."
	/>
</svelte:head>

<div class="text-center sm:px-8">
	<h1 class="select-none font-christmas text-7xl m-10 text-center">Donate</h1>

	<p>
		Donators can enable premium features on their Discord servers. Please contact me on <Link
			href="https://lnk.earth/discord">Discord</Link
		> before donating and tell me which servers you want to enable premium on.
	</p>
	<p class="my-4">
		<a href="https://lnk.earth/xmas-premium">
			<Button colour="bg-yellow-500" text="Donate on Ko-fi" />
		</a>
	</p>
</div>

// src/views/Donate.vue
<template>
  <div class='content'>
    <Navbar />

	<mdb-container> <!-- fluid -->
		<h1 class='noselect'>Donate</h1>
		<p>
			Donators can enable premium features on their Discord servers. Please contact me on <a href='https://go.eartharoid.me/discord'>Discord</a> before donating and tell me which servers you want to enable premium on. Then donate on <a href='https://ko-fi.com/eartharoid'>Ko-fi</a>.
		</p>
		<a href='https://go.eartharoid.me/xmas-premium'>
					<mdb-btn color='warning'>Donate</mdb-btn> <!-- color='primary' -->
		</a>
	</mdb-container>

	<Footer />
  </div>
</template>

<script>
// @ is an alias to /src
import Navbar from '@/components/Navbar.vue';
import Footer from '@/components/Footer.vue';

import {
	mdbBtn,
	mdbContainer,
	// mdbIcon,
} from 'mdbvue';

export default {
  name: 'Donate',
  components: {
	Navbar,
	Footer,
	mdbBtn,
	mdbContainer,
  }
};
</script>

<style scoped>
	.content {
		text-shadow: 5px 5px 10px black;
		text-align: center;
	}

	h1 {
		font-family: 'MerryChristmas';
		font-size: 5rem;
		margin-bottom: 2rem;
	}
</style>
